GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY2ODI3MTU3OCwiZXhwIjoxNjY4MjcxNTk4fQ._ZAsFkyk_k3otcX4xko2SIXuECvG3wEfXaFHxC0wLfY
###
DELETE http://localhost:4000/logout
Content-Type: : application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY2ODI3MzMyOX0.b7hmckmj0JITLaLEeWUPHEK8Sifn7dJ7BTtfk3_ifS8"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWxleCIsImlhdCI6MTY2ODI3MzMyOX0.b7hmckmj0JITLaLEeWUPHEK8Sifn7dJ7BTtfk3_ifS8"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Alex"
}